import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_neo4j import Neo4jGraph, GraphCypherQAChain

load_dotenv(override=True)

# Module-level singletons. These get built ONCE per process, the first time
# run_ast_graph_rag() is called, and then reused for every subsequent call —
# whether that's from this script's __main__ block or from evaluate_hallucination.py
# looping over a whole eval set. This is what lets you query/evaluate repeatedly
# without re-touching build_kg.py.
_graph = None
_chain = None


def get_graph() -> Neo4jGraph:
    """Connect to the existing (already-built) Neo4j KG. Assumes build_kg.py has
    already been run — this never writes AST data itself."""
    global _graph
    if _graph is None:
        print("Connecting to existing Neo4j knowledge graph...")
        _graph = Neo4jGraph(
            url=os.getenv("NEO4J_URI"),
            username=os.getenv("NEO4J_USERNAME", "neo4j"),
            password=os.getenv("NEO4J_PASSWORD"),
        )
        _graph.refresh_schema()
    return _graph


def get_chain() -> GraphCypherQAChain:
    """Build the Cypher QA chain once per process and cache it."""
    global _chain
    if _chain is None:
        llm = ChatGoogleGenerativeAI(
            model=os.getenv("GEMINI_MODEL", "gemini-1.5-flash"),
            temperature=0.0,
        )
        _chain = GraphCypherQAChain.from_llm(
            llm=llm,
            graph=get_graph(),
            verbose=False,
            allow_dangerous_requests=True,
            return_intermediate_steps=True,  # crucial for hallucination evaluation
        )
    return _chain


def run_ast_graph_rag(query: str):
    """
    Executes a query against the AST-mapped Knowledge Graph.
    Returns (context, answer):
      - context: the raw Cypher/graph traversal results, used as ground truth
        for hallucination scoring.
      - answer: the natural-language answer generated by the LLM.
    Safe to call in a loop — the graph connection and chain are reused.
    """
    chain = get_chain()
    try:
        response = chain.invoke({"query": query})
        answer = response.get("result", "I don't know the answer.")
        intermediate_steps = response.get("intermediate_steps", [])
        context = str(intermediate_steps) if intermediate_steps else "No graph context retrieved."
        return context, answer
    except Exception as e:
        return f"ERROR: {e}", "Error generating answer."


if __name__ == "__main__":
    test_query = "Which components are rendered inside App.jsx?"
    print(f"\nTesting Query: '{test_query}'")

    retrieved_context, final_answer = run_ast_graph_rag(test_query)

    print("\n--- RETRIEVED AST CONTEXT ---")
    print(retrieved_context)
    print("\n--- GENERATED ANSWER ---")
    print(final_answer)